-- CREATE DATABASE JOINPRACTISE;
-- CREATING THE DATABASE
USE JOINPRACTISE;
-- CREATING TABLE
CREATE TABLE PROJECTS (
    projects_id INT PRIMARY KEY,
    ENROLLMENT_ID INT,
    PROJECT_NAME VARCHAR(255),
    PROJECT_TEACHER VARCHAR(255)
);
-- INSERTING THE RECORDS 
INSERT INTO PROJECTS (projects_id, ENROLLMENT_ID, PROJECT_NAME, PROJECT_TEACHER)
VALUES
    (101, 153, 'E-commerce_Website', 'Faraza_doja'),
    (102, 249, 'RECIPE_GENERATOR', 'NAZIYA_TASBEE'),
    (103, 207, 'SYNTACTIC_ANALYSIS', 'SYED_ALI'),
    (104, 248, 'REAL_STATE_WEBSITE', 'Faraza_doja');
    -- ALTER COMMAND IS USE TO CHANGE NAME OF COLUMN NAME TABLE NAME ADDING COLUMN OR DELETING COLUMN BASICALLY USED TO UPDATING THE TABLE
-- ADDING COLUMN
ALTER TABLE PROJECTS ADD COLUMN KAIFBHAI INT ;
SELECT *FROM PROJECTS;	
-- CHANGING COLUMN NAME  
ALTER TABLE PROJECTS CHANGE COLUMN KAIFBHAI KAIFSHAIKH INT ;
SELECT *FROM PROJECTS;	
-- DELETING COLUMN NAME 
ALTER TABLE PROJECTS DROP COLUMN KAIFSHAIKH;
SELECT *FROM PROJECTS;	
-- UPDATE COMMAND USE OF SET KEYWORD
UPDATE PROJECTS SET PROJECT_TEACHER="FARAZ DOJA " WHERE projects_id =101;
UPDATE PROJECTS SET ENROLLMENT_ID=248 WHERE  projects_id=104;
-- DELETE KEYWORD 
DELETE FROM PROJECTS WHERE projects_id=1;
