-- CREATE DATABASE JOINPRACTISE;
-- CREATING THE DATABASE
USE JOINPRACTISE;
-- CREATING TABLE
CREATE TABLE PROJECTS (
    projects_id INT PRIMARY KEY,
    ENROLLMENT_ID INT,
    PROJECT_NAME VARCHAR(255),
    PROJECT_TEACHER VARCHAR(255)
);
-- INSERTING THE RECORDS 
INSERT INTO PROJECTS (projects_id, ENROLLMENT_ID, PROJECT_NAME, PROJECT_TEACHER)
VALUES
    (101, 153, 'E-commerce_Website', 'Faraza_doja'),
    (102, 249, 'RECIPE_GENERATOR', 'NAZIYA_TASBEE'),
    (103, 207, 'SYNTACTIC_ANALYSIS', 'SYED_ALI'),
    (104, 248, 'REAL_STATE_WEBSITE', 'Faraza_doja');
    
-- USE OF BETWEEN ,AND OPERATOR  USE IN RANGE ETC..
SELECT *FROM PROJECTS WHERE  projects_id BETWEEN 101 AND 103;
-- USE OF OR OPERATOR , USE IF WANT TO SELECT ONE OR MORE TYPE 
SELECT *FROM PROJECTS WHERE projects_id=103 or PROJECT_NAME="RECIPE_GENERATOR"; -- IT WILL GIVE ID=103 AND ALSO PROJECT-> RECIPE GENRATOR
SELECT *FROM PROJECTS where projects_id=101 OR PROJECT_NAME="E-commerce_Website";
