-- CREATE DATABASE JOINPRACTISE;
-- CREATING THE DATABASE
USE JOINPRACTISE;
-- CREATING TABLE
CREATE TABLE PROJECTS (
    projects_id INT PRIMARY KEY,
    ENROLLMENT_ID INT,
    PROJECT_NAME VARCHAR(255),
    PROJECT_TEACHER VARCHAR(255)
);
-- INSERTING THE RECORDS 
INSERT INTO PROJECTS (projects_id, ENROLLMENT_ID, PROJECT_NAME, PROJECT_TEACHER)
VALUES
    (101, 153, 'E-commerce_Website', 'Faraza_doja'),
    (102, 249, 'RECIPE_GENERATOR', 'NAZIYA_TASBEE'),
    (103, 207, 'SYNTACTIC_ANALYSIS', 'SYED_ALI'),
    (104, 248, 'REAL_STATE_WEBSITE', 'Faraza_doja');
    
-- SORTING THE TABLE USING ORDER BY ORDER BY USE FOR SORTING THE TABLE IT TAKE PATICULAR COLUMN NAME EITH ORDER BY 
-- GIVE THE RESULT IN THE FORM OF 101,102,103,104 IN SORTED ORDER
SELECT *FROM PROJECTS ORDER BY projects_id ; 
-- USE OF DISC IN SORTING 
-- IF YOU WANT TO SORT IN REVERSE ORDER LIKE 105,104,103,103 YOU WILL USE DESC OPERATOR 
SELECT *FROM PROJECTS ORDER BY  projects_id DESC;
-- ANOTHER EXAMPLE
select *from PROJECTS order by ENROLLMENT_ID DESC;